### ISSUE TITLE
Use without Ionic

### ISSUE THREAD

**Issue by tominou** [tobyherrmann/cordova-plugin-google-consent#1]
Hi,

How to use it with Cordova but without Ionic?

Thank you

**Comment by tobyherrmann** [comment]
You can also call the methods directly, without using the typescript wrapper for ionic.

```javascript
window['Consent'].verifyConsent(publisherIds, privacyPolicyUrl, showProVersionOption, isDebug,
				function(result) {/* do something with the result */},
				function(error) {/* handle the error case */}
			);
			
			
window['Consent'].changeConsentDecision(privacyPolicyUrl, showProVersionOption,
				function(result) {/* do something with the result */},
				function(error) {/* handle the error case */}
			);
```

**Comment by tominou** [comment]
Thank you for the answer ^^

**Comment by tominou** [comment]
I get an error: `Error: consent form can be used with custom provider selection only.`
How can i set the providers?

Thank you again

**Comment by tobyherrmann** [comment]
According to Google Consent SDK documentation (https://developers.google.com/admob/android/eu-consent).

You have to met two points for using Consent SDK:
- do not use AdMob Mediation
- do not use more than 12 ad technology providers (this one you have to change, default is a set from google with 200 providers or something)

So change it in your AdMob account (https://apps.admob.com/v2/pubcontrols/eu-user-consent) and wait a few hours for the setting to become active.
