### ISSUE TITLE
build error local variable callbackContext is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by alesgraz** [tobyherrmann/cordova-plugin-google-consent#3]
Hi, 
thanks very much for your work, I'm facing with build errors like the one pasted below. Could you suggest a solution? thanks.

src\ch\herrmanntech\cordova\consent\Consent.java:55: error: local variable callbackContext is accessed from within inner class; needs to be declared final
                                        askForConsent(callbackContext, privacyPolicyUrl, showProVersionOption);

**Comment by tobyherrmann** [comment]
Please update the plugin to version "0.1.2" and try again.
