### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by mihawk007** [tobyherrmann/cordova-plugin-google-consent#4]
HI,
i have a problem After Adding the google consent Plugin To my project i can't build the app 

please can i get some help. this is what i get in my terminal

and thank you for the hard work in this great plugin.

/ProjectCordova/platforms/android/src/ch/herrmanntech/cordova/consent/Consent.java:94: error: local variable privacyPolicyUrl is accessed from within inner class; needs to be declared final
					askForConsent(cb, privacyPolicyUrl, showProVersionOption);
					                  ^
/ProjectCordova/platforms/android/src/ch/herrmanntech/cordova/consent/Consent.java:94: error: local variable showProVersionOption is accessed from within inner class; needs to be declared final
					askForConsent(cb, privacyPolicyUrl, showProVersionOption);
					                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /ProjectCordova/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

regards,

**Comment by tobyherrmann** [comment]
Please try again with the new version 0.1.3

**Comment by mihawk007** [comment]
thank you very much for your help its working now You really saved my life hhhhhhh, i wish you the best.
