### ISSUE TITLE
boolean isInEea = consentInformation.isRequestLocationInEeaOrUnknown();

### ISSUE THREAD

**Issue by DeathYouki** [tobyherrmann/cordova-plugin-google-consent#6]
I have been encountering this error while building or running on emulator, the build actually fails because of it. I think it's relative to the last update, because I have it working older app (beginning of August) before the update.

\platforms\android\src\ch\herrmanntech\cordova\consent\Consent.java:74: error: local variable consentInformation is accessed from within inner class; needs to be declared final
                                boolean isInEea = consentInformation.isRequestLocationInEeaOrUnknown();

**Comment by DeathYouki** [comment]
A quick workaround : 
I copied an older "\platforms\android\src\ch\herrmanntech\cordova\consent\Consent.java" and replaced it on the new app. I'll be using this solution till you guys fix it 😛

**Comment by tobyherrmann** [comment]
fixed in package version 0.2.1

**Comment by DeathYouki** [comment]
Thank you. 😄
