### ISSUE TITLE
phonegap build error

### ISSUE THREAD

**Issue by DScotULuv** [tobyherrmann/cordova-plugin-google-consent#7]
hi there, i cant seem to build on adobe phonegap.
i tried all the versions but get this error;
******************************************************************************************
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find any matches for com.google.android.ads.consent:consent-library:+ as no versions of com.google.android.ads.consent:consent-library are available.
     Required by:
         project :
*******************************************************************
have you seen this before?
possibly a malformed <plugin> declaration, most recent attempt ( <plugin name="cordova-plugin-google-consent" source="npm" spec="~0.2.1" />      )

**Comment by tobyherrmann** [comment]
Never seen this, I have only experiencies with Ionic not Phonegap. There it is loaded with gradle from maven during the build. Maybe you have to include maven repositories in your build process.
There it is available: https://mvnrepository.com/artifact/com.google.android.ads.consent/consent-library

**Comment by DScotULuv** [comment]
thanks for the fast response, after a quick look about i think your correct but fixing this may be out of my depth :)
